[DF-47]_testSearchingBooksResults is added with dataprovider
DimaZadrutsiy/DemoQA_JAVA pull request #28
Opened 2023-01-06 20:57 UTC by JuliaUA

testSearchingBooksResult is added with dataprovider

2023-01-06 21:04 UTC, maksymiasko approved these changes

2023-01-07 08:06 UTC, yuriiormson requested changes

2023-01-07 08:06 UTC, yuriiormson commented on src/test/java/tests/BookStoreApplicationTest/BookStoreApplicationTest.java
> +        Assert.assertEquals(actualFirstBookFound, expectedFirstBookFound);
searchingBookResult.get(0) а це в метод винести не можна ? і це searchingBookResult.size();

я не розумію навіщо окремі змінні для зберігання результату. Чи це особливість DataProvider ?

подивись на мій тест testElementsList()

2023-01-07 08:17 UTC, yuriiormson approved these changes

2023-01-07 09:17 UTC, JuliaUA commented on src/test/java/tests/BookStoreApplicationTest/BookStoreApplicationTest.java
> +        Assert.assertEquals(actualFirstBookFound, expectedFirstBookFound);
Методы зробила, так дійсно красивіше :)
Щодо створення окремої змінної з префіксом actual- так зручніше і більш читабельно, мені здається.
Ірина підтримувала таку практику, Настя робила як ти, як каже Сергій - це "вкусовщина".

2023-01-07 09:19 UTC, yuriiormson approved these changes

2023-01-07 09:30 UTC, merged