[DF-64]testSelectAllTabsInGrid[Interactions/Selectable]
DimaZadrutsiy/DemoQA_JAVA pull request #48
Opened 2023-01-11 20:38 UTC by maksymiasko

added testSelectAllTabsInGrid
added test Priority
renamed variables 

[DF-64]- https://fem22.atlassian.net/jira/software/c/projects/DF/boards/1?modal=detail&selectedIssue=DF-6

2023-01-12 08:16 UTC, yuriiormson requested changes

2023-01-12 08:16 UTC, yuriiormson commented on src/test/java/tests/InteractionTests/SelectableTest.java
> +        Assert.assertEquals(actualClassNameBeforeSelect, className);
Expected I'm still waiting)

2023-01-12 15:05 UTC, DimaZadrutsiy commented
> > 
> 
> Зробив нове посилання на Jira

Ще треба дописати expected в Asert

2023-01-13 05:32 UTC, yuriiormson approved these changes

2023-01-13 08:33 UTC, KristinaPereselkina approved these changes

2023-01-13 08:34 UTC, merged