[DF-77] testHeaderNames[Elements/Links]
DimaZadrutsiy/DemoQA_JAVA pull request #55
Opened 2023-01-14 18:48 UTC by KristinaPereselkina

2023-01-15 17:02 UTC, maksymiasko approved these changes

2023-01-16 08:48 UTC, DimaZadrutsiy approved these changes

2023-01-16 08:50 UTC, DimaZadrutsiy requested changes
Привіт ні бачу, Link на Jira.

2023-01-16 10:29 UTC, DimaZadrutsiy approved these changes

2023-01-16 15:24 UTC, merged